### ISSUE TITLE
netcdf

### ISSUE THREAD

**Issue by ben-williams** [amoeba/netcdf-wasm#1]
i think that a clear methodology for handling these files for laypeople (aka biologists) would be a worthy venture, they are not self-evident when first approached. possibly this exists? haven't looked into it.

**Comment by amoeba** [comment]
Hey @ben-williams, thanks for the note. This project is specifically for making the NetCDF libraries available in web browsers and I'll want to put examples/demos so I might touch on this, if only at a shallow a level.

For working with netcdf files, you might like the vignette in `tidync`, https://docs.ropensci.org/tidync/articles/netcdf-with-tidync.html.

Edit: Also https://ropensci.org/blog/2019/11/05/tidync/

**Comment by ben-williams** [comment]
Well that is handy, nice!
